services:
  # PostgreSQL Database
  - type: pserv
    name: meetuptravel-db
    plan: free
    env: postgres
    region: singapore
    disk:
      name: meetuptravel-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

  # Backend API Service
  - type: web
    name: meetuptravel-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: singapore
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromService:
          type: pserv
          name: meetuptravel-db
          property: connectionString
          envVarName: DATABASE_URL
      - key: SPRING_DATASOURCE_USERNAME
        fromService:
          type: pserv
          name: meetuptravel-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromService:
          type: pserv
          name: meetuptravel-db
          property: password
    buildCommand: mvn -f backend/pom.xml clean package -DskipTests
    startCommand: java -jar backend/target/backend-0.0.1-SNAPSHOT.jar

  # Frontend Service
  - type: web
    name: meetuptravel-frontend
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm install -g serve && serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: REACT_APP_API_URL
        value: https://meetuptravel-backend.onrender.com/api

  # Admin Frontend Service
  - type: web
    name: meetuptravel-admin
    runtime: node
    plan: free
    buildCommand: cd frontend-admin && npm install && npm run build
    startCommand: cd frontend-admin && npm install -g serve && serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: REACT_APP_API_URL
        value: https://meetuptravel-backend.onrender.com/api 